---
- name: Install libpam-pwquality using APT
  package:
    name: libpam-pwquality
    state: present

# - name: Configure pwquality settings in /etc/security/pwquality.conf
#   lineinfile:
#     path: /etc/security/pwquality.conf
#     line: "{{ item }}"
#     create: yes
#     state: present
#   with_items:
#     - "minlen = 12"   # Minimum password length.
#     - "dcredit = -1"  # At least one digit
#     - "ucredit = -1"  # At least one uppercase letter
#     - "lcredit = -1"  # At least one lowercase letter
#     - "ocredit = -1"  # At least one special character
#     - "maxretry = 3"  # Max retries before failure
#     - "enforce_for_root"  # Enforces policy even for root

#     # The negative values in the configuration line above inform pam_pwquality that it must have at least “one of” for that category.

# - name: Ensure PAM uses pwquality for password enforcement
#   lineinfile:
#     path: /etc/pam.d/common-password
#     regexp: '^password\s+requisite\s+pam_pwquality.so'
#     line: "password requisite pam_pwquality.so retry=3"
#     state: present
#   when: ansible_os_family == "Debian"

- name: Configure pam_pwquality
  lineinfile:
    path: "/etc/pam.d/common-password"
    regexp: "pam_pwquality.so"
    line: "password required pam_pwquality.so minlen=12 lcredit=-1 ucredit=-1 dcredit=-1 ocredit=-1 retry=3 enforce_for_root"
    state: present