- name: Ensure group "devops" exists
  group:
    name: devops
    state: present

- name: Create the user 'jaywon' and assign to 'devops' group
  user:
    name: jaywon
    groups: devops
    append: yes
    shell: /bin/bash
    state: present
    password: $6$DXJHVHIaZlk8SrZ7$bemd43xJ5h7fWP5t8sevg2zdolszPUHS5iDrTuD8OT7Jio.Fv1m/2F8GItOJxvcaT122QBpiUe645frYfuZ//0

- name: Create a directory named 'engineering'
  file:
    path: /opt/engineering
    state: directory
    owner: root
    group: devops
    mode: '0750'

# - name: Force user 'jaywon' to change password on first login
#   command: chage -d 0 jaywon

- name: Create a file inside the 'engineering' directory
  file:
    path: "/opt/engineering/private-info.txt"
    state: touch
    owner: jaywon
    group: devops
    mode: '0770'